baseurl      = "https://vinculeiro.github.io/distritoZero/"
enableRobotsTXT = true

defaultContentLanguage           = "gl"
defaultContentLanguageInSubdir   = false

hasCJKLanguage = false

[pagination]
    pagerSize = 5
